# Generated by Django 2.2.3 on 2019-07-24 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job_Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='bio',
            name='job_title',
        ),
    ]
