# Generated by Django 2.2.3 on 2019-07-24 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_auto_20190724_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='icon',
            field=models.TextField(blank=True, default='example of css class: <i class="lnr lnr-laptop-phone"></i> ', null=True),
        ),
    ]
