# Generated by Django 2.2.3 on 2019-07-24 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_auto_20190724_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('Picture', models.ImageField(upload_to='Testimonial/')),
            ],
        ),
    ]
