# Generated by Django 2.2.3 on 2019-07-24 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_testimonial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonial',
            old_name='Picture',
            new_name='picture',
        ),
    ]
