# Generated by Django 2.2.3 on 2019-07-25 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0008_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coding_Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=255)),
                ('level', models.CharField(default='95%', max_length=255)),
                ('style_class', models.TextField(default='skill-percentage skill-1')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(max_length=255)),
                ('year', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('overview', models.TextField(blank=True, default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('period', models.CharField(max_length=255)),
                ('overview', models.TextField(blank=True, default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technology', models.CharField(max_length=255)),
                ('level', models.CharField(default='95%', max_length=255)),
                ('style_class', models.TextField(default='skill-percentage skill-5')),
            ],
        ),
    ]
