# Generated by Django 2.2.3 on 2019-08-15 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='ajax_id',
            field=models.CharField(default='#projects', max_length=255),
        ),
    ]
