# Generated by Django 2.2.3 on 2019-09-08 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20190908_2012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='project',
        ),
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ManyToManyField(blank=True, null=True, related_name='projects', to='projects.Images'),
        ),
    ]
